insert into location (id, street_address, postal_code, city, state_province, country_id) values (1, '7999 Ridge Oak Plaza', '28805', 'Asheville', 'North Carolina', 63);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (2, '903 Trailsway Hill', '11205', 'Brooklyn', 'New York', 56);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (3, '3859 Bluestem Circle', '28278', 'Charlotte', 'North Carolina', 46);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (4, '40891 Chive Center', '18706', 'Wilkes Barre', 'Pennsylvania', 59);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (5, '3 Bellgrove Road', '38197', 'Memphis', 'Tennessee', 57);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (6, '48560 Lerdahl Hill', '20918', 'Silver Spring', 'Maryland', 59);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (7, '46070 Doe Crossing Park', '32520', 'Pensacola', 'Florida', 76);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (8, '121 Glacier Hill Crossing', '84115', 'Salt Lake City', 'Utah', 96);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (9, '346 Dahle Crossing', '94147', 'San Francisco', 'California', 100);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (10, '66 Grayhawk Junction', '11436', 'Jamaica', 'New York', 37);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (11, '78 International Court', '20409', 'Washington', 'District of Columbia', 62);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (12, '9212 Burning Wood Plaza', '98175', 'Seattle', 'Washington', 19);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (13, '073 Colorado Drive', '90060', 'Los Angeles', 'California', 97);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (14, '81713 Bultman Plaza', '88546', 'El Paso', 'Texas', 85);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (15, '6 Tennessee Court', '94302', 'Palo Alto', 'California', 20);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (16, '6100 Pierstorff Crossing', '33954', 'Port Charlotte', 'Florida', 7);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (17, '6043 Forest Run Point', '34210', 'Bradenton', 'Florida', 52);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (18, '608 Cherokee Lane', '30375', 'Atlanta', 'Georgia', 67);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (19, '27 Kinsman Crossing', '73109', 'Oklahoma City', 'Oklahoma', 31);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (20, '76 Stoughton Crossing', '15274', 'Pittsburgh', 'Pennsylvania', 71);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (21, '03 Park Meadow Pass', '08608', 'Trenton', 'New Jersey', 78);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (22, '4 Springview Circle', '17110', 'Harrisburg', 'Pennsylvania', 24);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (23, '22257 Mesta Park', '77299', 'Houston', 'Texas', 64);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (24, '78 Little Fleur Trail', '19805', 'Wilmington', 'Delaware', 78);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (25, '63483 Melby Terrace', '94807', 'Richmond', 'California', 91);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (26, '2 Kinsman Circle', '76129', 'Fort Worth', 'Texas', 32);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (27, '3922 Express Point', '28263', 'Charlotte', 'North Carolina', 78);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (28, '3839 Banding Plaza', '06859', 'Norwalk', 'Connecticut', 86);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (29, '9 Birchwood Hill', '06922', 'Stamford', 'Connecticut', 35);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (30, '53 Hudson Circle', '64190', 'Kansas City', 'Missouri', 4);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (31, '48299 Hanover Drive', '60674', 'Chicago', 'Illinois', 3);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (32, '16308 Butterfield Parkway', '94273', 'Sacramento', 'California', 70);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (33, '8863 Lerdahl Crossing', '34210', 'Bradenton', 'Florida', 8);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (34, '69 Russell Parkway', '33158', 'Miami', 'Florida', 3);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (35, '74811 Brentwood Court', '65810', 'Springfield', 'Missouri', 79);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (36, '441 Blue Bill Park Park', '27150', 'Winston Salem', 'North Carolina', 67);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (37, '907 Morrow Plaza', '22212', 'Arlington', 'Virginia', 61);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (38, '465 Calypso Park', '20299', 'Washington', 'District of Columbia', 98);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (39, '713 Sutherland Junction', '75379', 'Dallas', 'Texas', 30);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (40, '44494 Eastwood Avenue', '85246', 'Chandler', 'Arizona', 92);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (41, '80 Straubel Park', '99260', 'Spokane', 'Washington', 46);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (42, '54 Bunting Place', '52405', 'Cedar Rapids', 'Iowa', 6);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (43, '16551 Stoughton Junction', '64153', 'Kansas City', 'Missouri', 8);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (44, '87 Oak Pass', '68583', 'Lincoln', 'Nebraska', 75);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (45, '575 Raven Center', '20310', 'Washington', 'District of Columbia', 68);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (46, '904 Delaware Center', '62776', 'Springfield', 'Illinois', 80);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (47, '51 Daystar Drive', '99517', 'Anchorage', 'Alaska', 14);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (48, '6 Prentice Parkway', '11470', 'Jamaica', 'New York', 16);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (49, '4 Homewood Plaza', '07104', 'Newark', 'New Jersey', 81);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (50, '12621 Rowland Park', '25705', 'Huntington', 'West Virginia', 5);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (51, '14 Sommers Terrace', '33190', 'Miami', 'Florida', 99);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (52, '957 Springview Alley', '19191', 'Philadelphia', 'Pennsylvania', 95);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (53, '58779 Ridgeview Way', '44485', 'Warren', 'Ohio', 95);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (54, '9 Hooker Center', '91499', 'Van Nuys', 'California', 100);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (55, '34491 Walton Way', '76711', 'Waco', 'Texas', 85);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (56, '61623 Monument Way', '55487', 'Minneapolis', 'Minnesota', 46);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (57, '573 Dottie Point', '73147', 'Oklahoma City', 'Oklahoma', 92);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (58, '66742 Laurel Circle', '39204', 'Jackson', 'Mississippi', 78);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (59, '2 Rowland Road', '75074', 'Plano', 'Texas', 62);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (60, '0 Independence Park', '46825', 'Fort Wayne', 'Indiana', 10);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (61, '0275 Nova Court', '00214', 'Portsmouth', 'New Hampshire', 2);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (62, '88 Graceland Circle', '46247', 'Indianapolis', 'Indiana', 59);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (63, '78256 Pepper Wood Road', '75062', 'Irving', 'Texas', 75);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (64, '44615 Utah Place', '71115', 'Shreveport', 'Louisiana', 52);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (65, '415 Marcy Court', '91841', 'Alhambra', 'California', 85);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (66, '04 Forest Dale Road', '33906', 'Fort Myers', 'Florida', 71);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (67, '19636 Helena Center', '11407', 'Jamaica', 'New York', 86);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (68, '2 Bay Crossing', '35236', 'Birmingham', 'Alabama', 87);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (69, '6 Jackson Plaza', '85305', 'Glendale', 'Arizona', 56);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (70, '5588 Pepper Wood Place', '30033', 'Decatur', 'Georgia', 33);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (71, '3 Transport Place', '55108', 'Saint Paul', 'Minnesota', 6);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (72, '4 Lighthouse Bay Terrace', '20088', 'Washington', 'District of Columbia', 45);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (73, '91 Comanche Place', '30380', 'Atlanta', 'Georgia', 91);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (74, '6161 Artisan Center', '48295', 'Detroit', 'Michigan', 43);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (75, '7441 Karstens Junction', '02142', 'Cambridge', 'Massachusetts', 63);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (76, '3907 Forest Run Hill', '02216', 'Boston', 'Massachusetts', 35);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (77, '93145 Saint Paul Point', '78225', 'San Antonio', 'Texas', 28);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (78, '2 Sachs Court', '91328', 'Northridge', 'California', 28);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (79, '0 Shoshone Alley', '78726', 'Austin', 'Texas', 7);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (80, '278 Karstens Way', '33543', 'Zephyrhills', 'Florida', 9);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (81, '45 Morningstar Hill', '62525', 'Decatur', 'Illinois', 71);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (82, '9 Mallory Park', '83757', 'Boise', 'Idaho', 2);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (83, '6 Mcguire Pass', '34985', 'Port Saint Lucie', 'Florida', 49);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (84, '2522 Tony Plaza', '20195', 'Reston', 'Virginia', 72);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (85, '450 Russell Drive', '29905', 'Beaufort', 'South Carolina', 62);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (86, '7976 Dexter Road', '02124', 'Boston', 'Massachusetts', 88);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (87, '75 Aberg Court', '62723', 'Springfield', 'Illinois', 2);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (88, '09552 Northport Way', '27717', 'Durham', 'North Carolina', 54);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (89, '3 Melrose Plaza', '84403', 'Ogden', 'Utah', 47);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (90, '8 Stuart Terrace', '48919', 'Lansing', 'Michigan', 16);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (91, '10250 Sheridan Point', '20073', 'Washington', 'District of Columbia', 77);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (92, '3165 Pepper Wood Street', '78682', 'Round Rock', 'Texas', 61);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (93, '365 Eagan Way', '73197', 'Oklahoma City', 'Oklahoma', 73);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (94, '572 American Ash Avenue', '05609', 'Montpelier', 'Vermont', 56);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (95, '46896 Corry Place', '96850', 'Honolulu', 'Hawaii', 97);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (96, '307 Heffernan Parkway', '79699', 'Abilene', 'Texas', 19);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (97, '4474 Bay Hill', '03804', 'Portsmouth', 'New Hampshire', 5);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (98, '82 Farmco Crossing', '32304', 'Tallahassee', 'Florida', 21);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (99, '728 Bultman Parkway', '76105', 'Fort Worth', 'Texas', 58);
insert into location (id, street_address, postal_code, city, state_province, country_id) values (100, '7812 Westport Alley', '31205', 'Macon', 'Georgia', 91);