insert into job (id, job_title, min_salary, max_salary, employee_id) values (1, 'Account Representative III', 1100, 5464, 21);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (2, 'Computer Systems Analyst II', 1956, 5012, 19);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (3, 'Information Systems Manager', 1992, 7591, 51);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (4, 'Statistician I', 1246, 7865, 27);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (5, 'Financial Analyst', 1739, 7107, 74);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (6, 'GIS Technical Architect', 1181, 5208, 83);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (7, 'Associate Professor', 1158, 8404, 41);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (8, 'Professor', 1189, 6217, 73);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (9, 'Sales Representative', 1480, 9964, 36);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (10, 'GIS Technical Architect', 1982, 9846, 87);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (11, 'Assistant Professor', 1339, 5456, 55);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (12, 'Environmental Specialist', 1715, 6763, 13);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (13, 'VP Quality Control', 1132, 9723, 39);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (14, 'Occupational Therapist', 1679, 9979, 3);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (15, 'Account Representative IV', 1874, 5750, 14);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (16, 'Quality Engineer', 1640, 7079, 24);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (17, 'Marketing Assistant', 1658, 7556, 2);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (18, 'VP Quality Control', 1534, 5677, 53);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (19, 'Editor', 1224, 8279, 60);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (20, 'Product Engineer', 1411, 8750, 98);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (21, 'Clinical Specialist', 1904, 7313, 74);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (22, 'Teacher', 1945, 8479, 43);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (23, 'Registered Nurse', 1772, 6346, 16);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (24, 'Tax Accountant', 1338, 8864, 80);
insert into job (id, job_title, min_salary, max_salary, employee_id) values (25, 'Recruiter', 1865, 7831, 13);